# Generated by Django 3.2.5 on 2021-07-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coruse',
            name='image',
            field=models.ImageField(default='courses/not_available.jpg', upload_to='courses/%Y/%m/%d/'),
        ),
    ]
